# Generated by Django 4.2 on 2024-07-02 05:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_tax"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tax",
            options={"verbose_name_plural": "Taxes"},
        ),
    ]
