# Generated by Django 4.2 on 2024-07-05 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0005_alter_tax_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorderitem",
            name="coupon",
            field=models.ManyToManyField(blank=True, to="store.coupon"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
