# Generated by Django 4.2 on 2024-07-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_cartorderitem_coupon_alter_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorder",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
