# Generated by Django 4.2 on 2024-07-06 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vendor", "0001_initial"),
        ("store", "0007_cartorder_stripe_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vendor.vendor",
            ),
        ),
    ]
