# Generated by Django 4.2 on 2024-07-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_alter_cartorder_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
